name: 'Gradle Wrapper Validation'
description: 'Validates Gradle Wrapper JAR Files'
author: 'Gradle'

inputs:
  min-wrapper-count:
    description: 'Minimum number expected gradle-wrapper.jar files found in the repository. Non-negative number. Higher number is useful in monorepos where each project might have their own wrapper.'
    required: false
    default: '1'
  allow-snapshots:
    description: 'Allow Gradle snapshot versions during checksum verification. Boolean, true or false.'
    required: false
    default: 'false'
  allow-checksums:
    description: 'Accept arbitrary user-defined checksums as valid. Comma separated list of SHA256 checksums (lowercase hex).'
    required: false
    default: ''

outputs:
  failed-wrapper:
    description: 'The path of the Gradle Wrapper(s) JAR that failed validation. Path is a relative path to git repository root. Multiple paths are separated by a | character.'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'shield'
  color: gray-dark
