name: 'Gradle Wrapper Validation'
description: 'Validates Gradle Wrapper JAR Files'
author: 'Gradle'

inputs:
  min-wrapper-count:
    description: 'Minimum number expected gradle-wrapper.jar files found in the repository. Non-negative number. Higher number is useful in monorepos where each project might have their own wrapper.'
    required: false
    default: '1'
  allow-snapshots:
    description: 'Allow Gradle snapshot versions during checksum verification. Boolean, true or false.'
    required: false
    default: 'false'
  allow-checksums:
    description: 'Accept arbitrary user-defined checksums as valid. Comma separated list of SHA256 checksums (lowercase hex).'
    required: false
    default: ''

outputs:
  failed-wrapper:
    description: 'The path of the Gradle Wrapper(s) JAR that failed validation. Path is a platform-dependent relative path to git repository root. Multiple paths are separated by a | character.'
    value: ${{ steps.wrapper-validation.outputs.failed-wrapper }}

runs:
  using: "composite"
  steps:
    - name: Wrapper Validation
      id: wrapper-validation
      uses: gradle/actions/wrapper-validation@v4
      with:
        min-wrapper-count: ${{ inputs.min-wrapper-count }}
        allow-snapshots: ${{ inputs.allow-snapshots }}
        allow-checksums: ${{ inputs.allow-checksums }}
      env:
        GRADLE_ACTION_ID: gradle/wrapper-validation-action

branding:
  icon: 'shield'
  color: gray-dark
